name: 03 - Workflow Runners

on: push

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: echo "This job is running on a(n) $RUNNER_OS runner."
  mac-echo:
    runs-on: mac-latest
    steps:
      - name: Show OS
        run: echo "This job is running on a(n) $RUNNER_OS runner."
  windows-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        shell: bash
        run: echo "This job is running on a(n) $RUNNER_OS runner."
