name: 03 - Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    # 2. Execute automated tests
    steps:
      # 0. Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      # 1. Install dependency
      - name: Install Dependencies
        run: npm ci
        working-directory: github-actions/04-using-actions/react-app
